config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get  "log_in"  => "sessions#new"
  post "log_in"  => "sessions#log_in"
  get  "log_out" => "sessions#log_out"

  # TODO: specify the routes so we don't have the unnecessary ones
  resources :users
  resources :clubs

  # TODO: I think there is a better way of doing this
  get "/clubs/:id/kick/:member_id" => "clubs#kick", as: "kick_member"
end

app/models/club.rb
class Club < ActiveRecord::Base
  validates_presence_of :name
  has_many :users

  def members
    users.where(owner: false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :club
  has_and_belongs_to_many :workouts
  validates_presence_of :email

  has_secure_password

  def self.authenticate(email, password)
    user = find_by(email: email)

    return false if user.nil?
    user.authenticate(password)
  end

  def full_name
    [first_name, last_name].join(' ')
  end

  def owner?
    owner
  end

  def member?
    !owner?
  end
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :club
  has_and_belongs_to_many :users

  validates_presence_of :title, :club
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  before_filter :authorize_owner!
  before_filter :authorize_correct_owner!, only: [:show]

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      current_user.club_id = @club.id
      current_user.save!
      redirect_to root_path, notice: 'Created club'
    else
      render :new
    end
  end

  def show
    @club = Club.find(params[:id])
  end

  def kick
    # TODO: This needs to check if the member belongs to that club

    user = User.find(params[:member_id])
    user.club_id = nil
    user.save!
    redirect_to club_path(params[:id]), notice: "Member kicked"
  end

private

  def club_params
    params.require(:club).permit(:name, :address)
  end

  def authorize_owner!
    if current_user.nil? || !current_user.owner?
      redirect_to root_url
    end
  end

  def authorize_correct_owner!
    redirect_to root_url unless current_user.club_id == params[:id].to_i
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Welcome, #{@user.email}"
    else
      flash.now.alert = "Invalid email or password"
      @user = User.new
      render "new"
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :owner)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  # TODO: Refactor
  def log_in
    email, password = params[:user].values_at(:email, :password)
    user = User.authenticate(email, password)

    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Welcome, #{user.email}"
    else
      flash.now.alert = "Invalid email or password"

      @user = User.new
      render :new
    end
  end

  def log_out
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end

private

  def user_params
    params.require(:user).permit(:email, :owner)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Created user'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash.now.notice = "Updated information"
    render :edit
  end

private

  # TODO: make a separate update_user_params

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :owner,
      :club_id,
      :password,
      :password_confirmation,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    map = {
      notice: 'info',
      success: 'success',
      error: 'danger',
      alert: 'warning',
    }
    "alert alert-#{map[flash_type.to_sym]}"
  end
end

app/views/clubs/index.html.erb
<h1>Clubs#index</h1>
<p>Find me in app/views/clubs/index.html.erb</p>

app/views/clubs/new.html.erb
<h2>Register club</h2>

<%= simple_form_for @club do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit 'Register' %>
<% end %>

app/views/clubs/show.html.erb
<h2><%= @club.name %></h2>

<h3>Members</h3>

<ul>
<% @club.members.each do |member| %>
  <li><%= member.email %> | <%= link_to "kick", kick_member_path(@club.id, member.id) %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubygyms</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Rubygyms</a>
      </div>

      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><p class="navbar-text">Logged in as <%= current_user.email %></p></li>
          <li><%= link_to "Log out", log_out_path %></li>
          <li><%= link_to "Update information", edit_user_path(current_user.id) %></li>
          <% if current_user.owner? %>
            <% if current_user.club %>
              <li><%= link_to "My club", club_path(current_user.club_id) %></li>
            <% else %>
              <li><%= link_to "Register club", new_club_path %></li>
            <% end %>
          <% end %>
        <% else %>
          <li><%= link_to "Log in", log_in_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container master-container">
    <h1>Rubygyms</h1>

    <% flash.each do |type, message| %>
      <div class="<%= bootstrap_flash_class(type) %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h2>Update account</h2>

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :birthday %>
  <% if current_user.member? %>
      <%= f.association :club %>
  <% end %>
  <%= f.submit 'Update' %>
<% end %>

app/views/users/new.html.erb
<h2>Create account</h2>

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :birthday %>
  <%= f.input :owner %>
  <%= f.input :password, required: true %>
  <%= f.input :password_confirmation, required: true %>
  <%= f.submit 'Create account' %>
<% end %>